theme: jekyll-theme-minimal
title: Shia's Midnight Channel
description: now available even when it's not midnight!
github_username: cristian-carotenuto
channel: "CH 04"
weather: "RAIN / FOG"
status: "NOW BROADCASTING"